### ISSUE TITLE
AskCode installation/indexing error

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#118]
**Describe the bug**

```
2023-09-11 18:31:02.525 [info] installed devchat-ask with python=3.11.4 at /Users/basicthinker/.chat/mamba/envs/devchat-ask/bin/python
2023-09-11 18:31:02.526 [info] Installation finished.
2023-09-11 18:31:02.630 [info] Running command: /Users/basicthinker/.chat/mamba/envs/devchat-ask/bin/python /Users/basicthinker/.vscode/extensions/merico.devchat-0.1.28/tools/askcode_index_query.py index . .+\.js$, .+\.ts$, .+\.jsx$, .+\.tsx$, .+\.java$, .+\.py$, .+\.go$, .+\.rb$, .+\.php$, .+\.cpp$, .+\.c$, .+\.cs$, .+\.swift$, .+\.rs$, .+\.sh$, .+\.bash$, .+\.zsh$, .+\.m$, .+\.mm$, .+\.h$, .+\.hpp$, .+\.hh$, .+\.html$, .+\.htm$, .+\.xhtml$, .+\.xml$, .+\.css$, .+\.scss$, .+\.sass$, .+\.less$, .+\.json$, .+\.yaml$, .+\.yml$, .+\.toml$, .+\.ini$, .+\.md$, .+\.markdown$, .+\.txt$, .+\.csv$, .+\.sql$, .+\.sqlite$, .+\.db$, .+\.hql$, .+\.psql$, .+\.pgsql$, .+\.plpgsql$
2023-09-11 18:31:02.992 [info] Traceback (most recent call last):
  File "/Users/basicthinker/.vscode/extensions/merico.devchat-0.1.28/tools/askcode_index_query.py", line 9, in <module>

2023-09-11 18:31:02.992 [info]     from chat.ask_codebase.store.qdrant import QdrantWrapper as Q, get_client
  File "chat/__init__.py", line 3, in init chat
ModuleNotFoundError: No module named 'dotenv'

2023-09-11 18:31:02.996 [error] Indexing failed: Traceback (most recent call last):
  File "/Users/basicthinker/.vscode/extensions/merico.devchat-0.1.28/tools/askcode_index_query.py", line 9, in <module>
    from chat.ask_codebase.store.qdrant import QdrantWrapper as Q, get_client
  File "chat/__init__.py", line 3, in init chat
ModuleNotFoundError: No module named 'dotenv'
```

**To Reproduce**
When AskCode is not installed, click on 'AskCode' (the icon in the bottom right). The installation/indexing process stops at the above step.

**Desktop:**
 - MacOS

**Comment by basicthinker** [comment]
The AskCode icon becomes not clickable after installation. Then why is there that icon? @runjinz It is better to merge AskCode into the DevChat state, with just one icon in the status bar.
